In [2]:
#使用pandas库，将表格数据文件读取到程序并转换为张量
import torch
import pandas as pd
import os

In [7]:
os.makedirs('data',exist_ok=True)
data_file=os.path.join('.','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [ ]:
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

pandas.core.frame.DataFrame

In [16]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
inputs['NumRooms']=inputs['NumRooms'].fillna(inputs['NumRooms'].mean())
inputs

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [17]:
inputs=pd.get_dummies(inputs,dummy_na=True)
inputs

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [20]:
X=torch.tensor(inputs.to_numpy(dtype=float))
y=torch.tensor(outputs.values,dtype=torch.float32).view(-1,1)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([[127500.],
         [106000.],
         [178100.],
         [140000.]]))